<?php

namespace FletesBundle\Repository;

use Doctrine\ORM\QueryBuilder;

use Doctrine\ORM\EntityRepository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository{
    
    public function pagina($pagina){
        $query = $this->createQueryBuilder('o')
        ->setMaxResults(10)
        ->setFirstResult(($pagina-1)*10)
        ->getQuery();
        
        $result = $query->getResult();
        return $result;
    }
    
    public function total(){
        $query = $this->createQueryBuilder('o')
        ->select('COUNT(o.id) as total')
        ->getQuery();
        return $query->getSingleScalarResult();
    }
    
    private function queryBusquedaBuilder($filtro){
       $builder = $this->createQueryBuilder('o');
       if(isset($filtro->origen)){
           $builder->andWhere('o.origen.gid=:origen');
           $builder->setParameter('origen',$filtro->origen->gid);
       } 
       
       if(isset($filtro->destino)){
           $builder->andWhere("(o.destino.gid=:destino or o.localidadesAceptadas like :ldestino)");
           $builder->setParameter('destino',$filtro->destino->gid);
           $builder->setParameter('ldestino',"%{$filtro->destino->gid}%");
       }
       
      return $builder;
    }
    
    public function busqueda($filtro){
        $builder = $this->queryBusquedaBuilder($filtro);
        $builder->setMaxResults(10);
        if(isset($filtro->pagina)){
            $builder->setFirstResult(($filtro->pagina-1)*10);
        }
        
        return $builder->getQuery()->getResult();
    }
    
    public function cantidadResultados($filtro){
        $builder = $this->queryBusquedaBuilder($filtro);
        $builder->select('COUNT(o.id) as total');
        return $builder->getQuery()->getSingleScalarResult();
    }
}
