security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FletesBundle\Entity\Usuario:
            id: fletes_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity:
                class: FletesBundle:Usuario

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        encode:
            pattern:  ^/sha512/*
            security: false
        
        encode:
            pattern:  ^/sha512/*
            security: false

        secured_area:
            pattern: ^/
            provider: usuarios
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /
                failure_forward: false
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    ~

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/formulario/?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/confirmar/.*/?$, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/ususario/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/clave/reset/?.*$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/confirmar_reseteo/?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ofertas$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oferta/b$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

