security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FletesBundle\Entity\Usuario:
            id: fletes_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity:
                class: FletesBundle:Usuario
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        encode:
            pattern:  ^/sha512/*
            security: false

        login:
            pattern:  ^/login$
            security: false
        
        secured_area:
            pattern:    ^/
            provider: usuarios
            form_login:
                # submit the login form here
                check_path: /login_check

                # the user is redirected here when they need to log in
                login_path: /login

                # login success redirecting options (read further below)
                always_use_default_target_path: true
                default_target_path: /

                # login failure redirecting options (read further below)
                failure_forward: false
            logout:
                path:   /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

